######### Buscar pelicula por el _id
http://localhost:3000/movie/title/joker

######### Login del usuario creado

POST  http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "paco",
    "password":"123456"
}


######### Logout del usuario
PATCH http://localhost:3002/user/logout
Content-Type: application/json

{
    "username": "azael",
    "password":"123"
}


######### Alquiler de peliculas segun el usuario.

post http://localhost:3005/user/profile/order
authorization: 5ddbc665585d3309484cc63e
Content-Type: application/json

{
    "title": "Joker"
}


######### Registro de Usuarios

POST http://localhost:3002/user/register
Content-Type: application/json

{
    "username": "alex",
    "password":"123",
    "email": "alex@gmail.com"
}

